# Generated by Django 3.2.6 on 2022-01-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPimet', models.IntegerField()),
                ('latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=10)),
                ('domain', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('actualizacion', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=10)),
                ('direccion', models.CharField(blank=True, max_length=10, null=True)),
                ('desde', models.DateField()),
                ('hasta', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emitido', models.DateField(auto_now_add=True)),
                ('modificado', models.DateField(auto_now=True)),
                ('valido', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Hielo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateField(auto_now_add=True)),
                ('texto', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pronostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateField(auto_now_add=True)),
                ('texto', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Situacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.CharField(max_length=40)),
                ('valorInicial', models.IntegerField(blank=True, null=True)),
                ('momentoInicial', models.DateField()),
                ('movimiento', models.CharField(blank=True, max_length=4, null=True)),
                ('evolucion', models.CharField(blank=True, max_length=10, null=True)),
                ('posicionInicial', models.TextField(blank=True, null=True)),
                ('posicionFinal', models.TextField(blank=True, null=True)),
                ('momentoFinal', models.DateField()),
                ('navtex', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
