# Generated by Django 3.2.6 on 2022-01-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pronostico',
            name='creado',
        ),
        migrations.AddField(
            model_name='aviso',
            name='activo',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
