# Generated by Django 3.2.6 on 2022-01-02 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0002_auto_20220102_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='boletines',
            field=models.ManyToManyField(to='AppMaritima.Boletin'),
        ),
        migrations.AddField(
            model_name='hielo',
            name='boletin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppMaritima.boletin'),
        ),
        migrations.AddField(
            model_name='pronostico',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppMaritima.area'),
        ),
        migrations.AddField(
            model_name='pronostico',
            name='boletin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppMaritima.boletin'),
        ),
        migrations.AddField(
            model_name='situacion',
            name='boletin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppMaritima.boletin'),
        ),
    ]
