# Generated by Django 3.2.6 on 2022-01-02 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0003_auto_20220102_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aviso',
            old_name='boletines',
            new_name='boletin',
        ),
    ]
