# Generated by Django 3.2.6 on 2022-01-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0004_rename_boletines_aviso_boletin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='description',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='area',
            name='domain',
            field=models.CharField(max_length=30),
        ),
    ]
