# Generated by Django 3.2.6 on 2022-01-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0005_auto_20220102_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletin',
            name='emitido',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='boletin',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='boletin',
            name='valido',
            field=models.DateTimeField(),
        ),
    ]
