# Generated by Django 3.2.6 on 2022-01-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0006_auto_20220102_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='desde',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
