# Generated by Django 3.2.6 on 2022-01-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0007_auto_20220103_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='area',
            field=models.ManyToManyField(to='AppMaritima.Area'),
        ),
    ]
