# Generated by Django 4.0.3 on 2022-03-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0011_auto_20220318_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='situacion',
            name='horaFinal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='situacion',
            name='horaInicial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='situacion',
            name='momentoFinal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='situacion',
            name='momentoInicial',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='situacion',
            name='posicionFinal',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='situacion',
            name='posicionInicial',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='situacion',
            name='sistema',
            field=models.CharField(max_length=60),
        ),
    ]
