# Generated by Django 4.0.4 on 2022-06-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0012_situacion_horafinal_situacion_horainicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='situacion',
            name='activo',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
