# Generated by Django 4.0.4 on 2022-06-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0014_remove_situacion_boletin_situacion_boletin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hielo',
            name='boletin',
        ),
        migrations.AddField(
            model_name='hielo',
            name='boletin',
            field=models.ManyToManyField(to='AppMaritima.boletin'),
        ),
    ]
