# Generated by Django 4.0.4 on 2022-06-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0017_remove_pronostico_boletin_pronostico_boletin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronostico',
            name='tipo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
