# Generated by Django 4.0.4 on 2022-06-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0018_pronostico_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='latitude',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='area',
            name='longitude',
            field=models.CharField(max_length=20),
        ),
    ]
