# Generated by Django 4.0.4 on 2022-06-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0019_alter_area_latitude_alter_area_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
