# Generated by Django 4.0.4 on 2022-06-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0020_alter_area_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='situacion',
            field=models.ManyToManyField(to='AppMaritima.situacion'),
        ),
    ]
