# Generated by Django 4.0.4 on 2022-06-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0021_aviso_situacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='provoca',
            field=models.CharField(default='PROVOKE', max_length=30),
        ),
    ]
