# Generated by Django 4.0.4 on 2022-07-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0022_aviso_provoca'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='orden',
            field=models.IntegerField(default=999),
        ),
    ]
