# Generated by Django 4.0.4 on 2022-07-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0024_aviso_navtex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='navtex',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
