# Generated by Django 4.0.4 on 2022-11-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0025_alter_aviso_navtex'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletin',
            name='pronosticosGuardados',
            field=models.CharField(default='0000000', max_length=60),
        ),
    ]
