# Generated by Django 4.0.4 on 2023-03-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0026_boletin_pronosticosguardados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situacion',
            name='movimiento',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
