# Generated by Django 4.0.4 on 2023-03-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0027_alter_situacion_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='situacion',
            name='actualizacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='situacion',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
