# Generated by Django 4.0.4 on 2023-07-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0028_situacion_actualizacion_situacion_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='situacion',
            name='esPresente',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
