# Generated by Django 4.0.4 on 2023-07-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0029_situacion_espresente'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='descriptionIngles',
            field=models.CharField(default='INGLES', max_length=50),
        ),
    ]
