# Generated by Django 4.0.4 on 2024-07-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0030_area_descriptioningles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='description',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='area',
            name='descriptionIngles',
            field=models.CharField(default='INGLES', max_length=80),
        ),
    ]
