# Generated by Django 4.0.4 on 2024-07-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0031_alter_area_description_alter_area_descriptioningles'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletin',
            name='pronosticosOlasSHN',
            field=models.CharField(default='0000000', max_length=600000),
        ),
    ]
