# Generated by Django 4.0.4 on 2024-08-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0032_boletin_pronosticosolasshn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletin',
            name='pronosticosOlasSHN',
            field=models.TextField(default='0000000'),
        ),
    ]
