# Generated by Django 4.0.4 on 2024-08-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0033_alter_boletin_pronosticosolasshn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('referer', models.CharField(max_length=100)),
                ('expiration', models.IntegerField()),
                ('f', models.CharField(max_length=10)),
            ],
        ),
    ]
