# Generated by Django 4.0.4 on 2024-08-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0034_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='sur60',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='situacion',
            name='sur60',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='situacion',
            name='navtex',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
