# Generated by Django 4.0.4 on 2024-11-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0035_aviso_sur60_situacion_sur60_alter_situacion_navtex'),
    ]

    operations = [
        migrations.AddField(
            model_name='situacion',
            name='extension',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
