# Generated by Django 4.0.4 on 2024-11-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0039_alter_situacion_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situacion',
            name='extension',
            field=models.CharField(blank=True, choices=[('', ' '), ('COLD FRONT', 'FRENTE FRIO')], max_length=50, null=True),
        ),
    ]
