# Generated by Django 4.0.4 on 2024-11-21 18:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0043_alter_situacion_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(default='Dconocida', srid=4326),
        ),
        migrations.AddField(
            model_name='area',
            name='name',
            field=models.CharField(default='Desconocida', max_length=100),
        ),
    ]
