# Generated by Django 4.0.4 on 2024-11-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaritima', '0044_area_geom_area_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='area',
            name='name',
        ),
    ]
